<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\Debug\\' => array($vendorDir . '/symfony/debug'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'React\\Promise\\' => array($vendorDir . '/react/promise/src'),
    'React\\' => array($vendorDir . '/react/react/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Mdanter\\Ecc\\' => array($vendorDir . '/mdanter/ecc/src'),
    'FG\\' => array($vendorDir . '/fgrosse/phpasn1/lib'),
    'BitWasp\\Stratum\\' => array($vendorDir . '/bitwasp/stratum/src'),
    'BitWasp\\Buffertools\\' => array($vendorDir . '/bitwasp/buffertools/src/Buffertools'),
    'BitWasp\\Bitcoin\\' => array($vendorDir . '/bitwasp/bitcoin/src'),
);
