<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Pleo' => array($vendorDir . '/pleonasm/merkle-tree/src'),
    'JsonRPC' => array($vendorDir . '/fguillot/json-rpc/src'),
    'Guzzle\\Parser' => array($vendorDir . '/guzzle/parser'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'DrSlump' => array($vendorDir . '/rgooding/protobuf-php/library'),
    'Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib'),
    'BlockCypher' => array($vendorDir . '/blockcypher/php-client/lib'),
);
